title: Envoy Proxy

description: > # this means to ignore newlines until "baseurl:"
  Envoy is an open source edge and service proxy, designed for cloud-native applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pandoracoin.info" # the base hostname & protocol for your site, e.g. http://example.com

